import type { AdminOverview, SparkCreator, StudentSnapshot } from "./types";
import { pointsToNextTier, tierFromPoints } from "./points";

const YOU_ID = "you-ashwin";

function c(
  partial: Omit<SparkCreator, "tier"> & { tier?: SparkCreator["tier"] }
): SparkCreator {
  const points = partial.points;
  return {
    ...partial,
    tier: partial.tier ?? tierFromPoints(points),
  };
}

export const SPARK_CREATORS: SparkCreator[] = [
  c({
    id: "1",
    name: "Priya Raghavan",
    handle: "@priya.builds",
    initials: "PR",
    campus: "Hyderabad",
    team: "Alpha",
    points: 2840,
    followers: 12400,
    views: 482000,
    likes: 38400,
    comments: 4200,
    engagement: 9.2,
    rank: 1,
    prevRank: 2,
    streakWeeks: "6 wks",
    tags: ["Hot streak"],
    gritStatus: "qualified",
    weeksInactive: 0,
    consistencyScore: 96,
  }),
  c({
    id: "2",
    name: "Arjun K.",
    handle: "@arjun.codes",
    initials: "AK",
    campus: "Bengaluru",
    team: "Beta",
    points: 2210,
    followers: 9100,
    views: 310000,
    likes: 24100,
    comments: 2800,
    engagement: 8.1,
    rank: 2,
    prevRank: 1,
    streakWeeks: "5 wks",
    tags: ["Reels", "Tech"],
    gritStatus: "striking",
    weeksInactive: 0,
    consistencyScore: 92,
  }),
  c({
    id: "3",
    name: "Sneha M.",
    handle: "@sneha.creates",
    initials: "SM",
    campus: "Chennai",
    team: "Alpha",
    points: 1980,
    followers: 7700,
    views: 256000,
    likes: 19800,
    comments: 2100,
    engagement: 7.8,
    rank: 3,
    prevRank: 3,
    streakWeeks: "4 wks",
    gritStatus: "striking",
    weeksInactive: 0,
    consistencyScore: 88,
  }),
  c({
    id: "4",
    name: "Ravi T.",
    handle: "@ravi.tech",
    initials: "RT",
    campus: "Pune",
    points: 1540,
    followers: 5200,
    views: 148000,
    likes: 11200,
    comments: 980,
    engagement: 6.4,
    rank: 4,
    prevRank: 6,
    streakWeeks: "3 wks",
    gritStatus: "striking",
    weeksInactive: 0,
    consistencyScore: 80,
  }),
  c({
    id: "5",
    name: "Meera S.",
    handle: "@meera.stories",
    initials: "MS",
    campus: "Delhi",
    points: 1320,
    followers: 4800,
    views: 132000,
    likes: 9600,
    comments: 840,
    engagement: 6.1,
    rank: 5,
    prevRank: 4,
    streakWeeks: "4 wks",
    gritStatus: "at_risk",
    weeksInactive: 0,
    consistencyScore: 76,
  }),
  c({
    id: "6",
    name: "Sai Charan",
    handle: "@sai.frames",
    initials: "SC",
    campus: "Hyderabad",
    team: "Gamma",
    points: 1210,
    followers: 6100,
    views: 198000,
    likes: 18200,
    comments: 1600,
    engagement: 11.8,
    rank: 6,
    prevRank: 8,
    streakWeeks: "7 wks",
    gritStatus: "striking",
    weeksInactive: 0,
    consistencyScore: 94,
  }),
  c({
    id: "7",
    name: "Deepika Mundla",
    handle: "@deepika.daily",
    initials: "DM",
    campus: "Hyderabad",
    points: 1180,
    followers: 5400,
    views: 176000,
    likes: 14100,
    comments: 1200,
    engagement: 7.2,
    rank: 7,
    prevRank: 7,
    streakWeeks: "14 wks",
    tags: ["Consistent"],
    gritStatus: "striking",
    weeksInactive: 0,
    consistencyScore: 100,
  }),
  c({
    id: "8",
    name: "Harsha Polina",
    handle: "@harsha.polina",
    initials: "HP",
    campus: "Hyderabad",
    team: "Alpha",
    points: 1820,
    followers: 12400,
    views: 245600,
    likes: 22100,
    comments: 2100,
    engagement: 8.7,
    rank: 8,
    prevRank: 10,
    streakWeeks: "14 wks",
    isYou: false,
    gritStatus: "striking",
    weeksInactive: 0,
    consistencyScore: 98,
  }),
  c({
    id: "9",
    name: "Rohit Kumar",
    handle: "@rohit.rises",
    initials: "RK",
    campus: "Bengaluru",
    points: 980,
    followers: 3900,
    views: 98000,
    likes: 7200,
    comments: 610,
    engagement: 5.9,
    rank: 9,
    prevRank: 23,
    streakWeeks: "2 wks",
    tags: ["Fast rising"],
    gritStatus: "at_risk",
    weeksInactive: 0,
    consistencyScore: 64,
  }),
  c({
    id: "10",
    name: "Ananya Nair",
    handle: "@ananya.reels",
    initials: "AN",
    campus: "Chennai",
    points: 940,
    followers: 8200,
    views: 410000,
    likes: 31200,
    comments: 3400,
    engagement: 8.4,
    rank: 10,
    prevRank: 11,
    streakWeeks: "5 wks",
    gritStatus: "striking",
    weeksInactive: 0,
    consistencyScore: 85,
  }),
  // Fill ranks 11-57 lightly, then YOU at 58
  ...Array.from({ length: 47 }, (_, i) => {
    const n = i + 11;
    const pts = Math.max(200, 900 - (n - 11) * 12);
    return c({
      id: `r${n}`,
      name: `Creator ${n}`,
      handle: `@creator${n}`,
      initials: `C${n % 10}`,
      campus: (["Hyderabad", "Bengaluru", "Chennai", "Pune", "Delhi"] as const)[n % 5],
      points: pts,
      followers: Math.round(3500 - n * 40 + (n % 7) * 80),
      views: Math.round(80000 - n * 900),
      likes: Math.round(6000 - n * 70),
      comments: Math.round(500 - n * 5),
      engagement: Number((4 + (n % 5) * 0.4).toFixed(1)),
      rank: n,
      prevRank: n + ((n % 3) - 1),
      streakWeeks: `${(n % 8) + 1} wks`,
      gritStatus: n > 40 ? "at_risk" : "not_eligible",
      weeksInactive: n > 50 ? 2 : 0,
      consistencyScore: Math.max(40, 90 - n),
    });
  }),
  c({
    id: YOU_ID,
    name: "Ashwin Mehta",
    handle: "@ashwin.makes",
    initials: "AM",
    campus: "Hyderabad",
    team: "Alpha",
    points: 612,
    followers: 2100,
    views: 42000,
    likes: 3100,
    comments: 280,
    engagement: 5.2,
    rank: 58,
    prevRank: 64,
    streakWeeks: "3 wks",
    isYou: true,
    gritStatus: "at_risk",
    weeksInactive: 0,
    consistencyScore: 71,
  }),
];

export const CURRENT_STUDENT_ID = "8"; // Harsha on student dashboard
export const PINNED_LEADERBOARD_YOU_ID = YOU_ID;

export function getCreator(id: string) {
  return SPARK_CREATORS.find((x) => x.id === id)!;
}

export function getStudentSnapshot(): StudentSnapshot {
  const creator = { ...getCreator(CURRENT_STUDENT_ID), isYou: true };
  const next = pointsToNextTier(creator.points);
  return {
    creator,
    weekLabel: "WEEK 14 • COHORT 01",
    cohort: "COHORT 01",
    refreshNote: "Stats refresh Monday 00:00 IST",
    rankDelta: 2,
    pointsToNextTier: next.remaining,
    nextTier: next.next,
    goldTarget: 2500,
    followersDelta: 740,
    followersDeltaPct: 6.3,
    viewsDeltaPct: 18.5,
    engagementDeltaPct: 1.2,
    postsThisWeek: 5,
    postsDelta: 1,
    avgViews: 24200,
    avgViewsDeltaPct: 15.6,
    avgLikes: 2300,
    avgLikesDeltaPct: 10.3,
    avgComments: 210,
    avgCommentsDeltaPct: 8.1,
    performance: [
      { date: "Jul 10", views: 18000, points: 40, followers: 11660 },
      { date: "Jul 11", views: 22000, points: 55, followers: 11820 },
      { date: "Jul 12", views: 19500, points: 45, followers: 11910 },
      { date: "Jul 13", views: 28000, points: 70, followers: 12040 },
      { date: "Jul 14", views: 31000, points: 85, followers: 12180 },
      { date: "Jul 15", views: 26500, points: 60, followers: 12290 },
      { date: "Jul 16", views: 34000, points: 95, followers: 12400 },
    ],
    taskHistory: [
      { id: "t1", week: 14, title: "Weekly minimum — 2 shorts + 1 long-form", category: "Consistency", points: 10, status: "approved", date: "2026-07-16" },
      { id: "t2", week: 13, title: "Short-form hit 50K–100K views", category: "Performance", points: 30, status: "approved", date: "2026-07-09" },
      { id: "t3", week: 12, title: "Audience milestone — 10K followers", category: "Growth", points: 150, status: "approved", date: "2026-07-02" },
      { id: "t4", week: 11, title: "Collab Sprint participation", category: "Bonus", points: 25, status: "approved", date: "2026-06-25" },
      { id: "t5", week: 10, title: "Weekly minimum missed (1 short only)", category: "Consistency", points: 0, status: "missed", date: "2026-06-18" },
      { id: "t6", week: 9, title: "Long-form 10K–50K views", category: "Performance", points: 50, status: "approved", date: "2026-06-11" },
    ],
    journalSubmitted: 14,
    journalTotal: 24,
    programmeStart: "1 May 2026",
    programmeEnd: "31 Oct 2026",
    youAreHere: "You are here • 23 Jul",
    totalParticipants: 315,
  };
}

export function getAdminOverview(): AdminOverview {
  const creators = SPARK_CREATORS;
  const grit = {
    qualified: creators.filter((x) => x.gritStatus === "qualified").length,
    striking: creators.filter((x) => x.gritStatus === "striking").length,
    atRisk: creators.filter((x) => x.gritStatus === "at_risk" || x.gritStatus === "not_eligible").length,
  };
  return {
    weekLabel: "WEEK 14 • COHORT 01",
    dateRange: "May 10 - May 16, 2026",
    totalParticipants: 315,
    participantsDelta: 12,
    igConnectedPct: 100,
    totalFollowers: 1_250_000,
    followersDeltaPct: 8.7,
    totalViews: 24_800_000,
    viewsDeltaPct: 12.4,
    totalLikes: 2_350_000,
    likesDeltaPct: 11.2,
    totalComments: 245_000,
    reelsPosted: 1842,
    newFollowers: 312,
    totalPointsDistributed: 98540,
    pointsDeltaPct: 9.4,
    totalEngagement: 2_350_000,
    engagementDeltaPct: 15.3,
    growthSeries: [
      { date: "May 10", followers: 1.12e6, views: 3.1e6, likes: 280000 },
      { date: "May 11", followers: 1.14e6, views: 3.4e6, likes: 295000 },
      { date: "May 12", followers: 1.16e6, views: 3.2e6, likes: 302000 },
      { date: "May 13", followers: 1.19e6, views: 3.8e6, likes: 318000 },
      { date: "May 14", followers: 1.21e6, views: 4.1e6, likes: 330000 },
      { date: "May 15", followers: 1.23e6, views: 3.9e6, likes: 341000 },
      { date: "May 16", followers: 1.25e6, views: 4.3e6, likes: 355000 },
    ],
    insights: [
      { label: "Highest Follower Growth", name: "Harsha Polina", value: "+820" },
      { label: "Highest Engagement Rate", name: "Sai Charan", value: "11.8%" },
      { label: "Most Consistent Creator", name: "Deepika Mundla", value: "7 posts" },
      { label: "Fastest Rising", name: "Rohit Kumar", value: "+14 ranks" },
      { label: "Most Viewed Reel", name: "Ananya Nair", value: "182K views" },
    ],
    needingAttention: [
      { label: "No post in 7+ days", count: 28 },
      { label: "Engagement dropped > 25%", count: 16 },
      { label: "Account is private", count: 7 },
      { label: "Scraping failed", count: 3 },
      { label: "Username changed", count: 2 },
    ],
    scrape: {
      tracked: 315,
      updatedToday: 312,
      failed: 3,
      lastSync: "Today 06:12 IST",
      nextSync: "Tomorrow 06:00 IST",
    },
    grit,
    submissions: { pending: 42, approved: 186, rejected: 11 },
    atRiskCount: 47,
  };
}

export const CAMPUSES = ["Hyderabad", "Bengaluru", "Chennai", "Pune", "Delhi"] as const;
